version: '3.3'
services:
  db:
    image: library/postgres:11.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: postgres
      PGDATA: /var/lib/postgresql/data/pg_data
    env_file:
      - .env
    restart: always
  web:
    build: .
    ports:
      - "80-85:80"
    environment:
      POSTGRES_HOST: db
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    restart: always
    links:
      - db
  nginx:
    image: library/nginx:1.17
    container_name: nginx
    volumes:
      - .default.conf:/etc/nginx/conf.d/.default.conf
    links:
      - web
    ports:
      - "8989:8989"
