# Generated by Django 3.0.5 on 2021-03-25 04:40

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('courier_type', models.CharField(choices=[('foot', 'Foot'), ('bike', 'Bike'), ('car', 'Car')], max_length=4, verbose_name='Courier type')),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('working_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('allowed_orders_weight', models.DecimalField(blank=True, decimal_places=4, default=10, max_digits=6, null=True, verbose_name='allowed_orders_weight')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(db_index=True, decimal_places=4, max_digits=6, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Weight')),
                ('region', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Region')),
                ('delivery_hours', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('courier_type', models.CharField(blank=True, choices=[('foot', 'Foot'), ('bike', 'Bike'), ('car', 'Car')], max_length=4, null=True, verbose_name='Courier type')),
                ('assign_time', models.DateTimeField(blank=True, null=True, verbose_name='assign_time')),
                ('complete_time', models.DateTimeField(blank=True, null=True, verbose_name='complete_time')),
                ('allow_to_assign', models.BooleanField(blank=True, default=True, null=True, verbose_name='allow_to_assign')),
                ('is_complete', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_complete')),
                ('assign_courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='api.Courier', verbose_name='assign_courier')),
            ],
        ),
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='assign_time')),
                ('is_complete', models.BooleanField(blank=True, default=False, null=True, verbose_name='is_complete')),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign', to='api.Courier')),
                ('orders', models.ManyToManyField(blank=True, related_name='assigns', to='api.Order', verbose_name='Orders')),
            ],
        ),
    ]
